spring:
  application:
    name: event-service
server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
kafka:
  topics:
    user: stats.user-actions.v1
    event: stats.events-similarity.v1