DROP SEQUENCE IF EXISTS REQ_ID_SEQ;
CREATE SEQUENCE IF NOT EXISTS REQ_ID_SEQ START WITH 1;

CREATE TABLE IF NOT EXISTS public.REQUESTS
(
    ID       bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 ),
    created  timestamp without time zone,
    requester  BIGINT NOT NULL,
    event_id BIGINT NOT NULL,
    status   character varying(64),
    CONSTRAINT req_pkey PRIMARY KEY (ID)
);