server:
  port: 8080

spring:
  application:
    name: gateway-server
  cloud:
    config:
      discovery:
        enabled: true # Use Eureka for discovering the Config Server
    gateway:
      discovery:
        locator:
          enabled: true # Enable dynamic routing via Eureka
      routes:
        - id: user-service-route
          uri: lb://user-service
          predicates:
            - Path=/admin/users/** # Admin user management

        - id: private-event-service-route
          uri: lb://event-service
          predicates:
            - Path=/users/**/events/** # Private event management for specific users

        - id: admin-event-service-route
          uri: lb://event-service
          predicates:
            - Path=/admin/events/** # Admin event management

        - id: public-event-service-route
          uri: lb://event-service
          predicates:
            - Path=/events/** # Public event endpoints

        - id: request-service-route
          uri: lb://request-service
          predicates:
            - Path=/users/**/requests/** # Participation requests management

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
