server:
  port: 8080

spring:
  application:
    name: gateway-server
  cloud:
    config:
      discovery:
        enabled: true # Use Eureka for discovering the Config Server
    gateway:
      discovery:
        locator:
          enabled: true # Enable dynamic routing via Eureka
      routes:
        - id: main-service-route
          uri: lb://main-service # Use Eureka load balancer for main-service
          predicates:
            - Path=/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
