eureka:
  client:
    registerWithEureka: true
    instance:
      preferIpAddress: true
      lease-renewal-interval-in-seconds: 30
      lease-expiration-duration-in-seconds: 90
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true

kafka:
  topics:
    user: stats.user-actions.v1
    event: stats.events-similarity.v1

spring:
  application:
    name: aggregator
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations:
            - classpath:config/{application}