spring:
  application:
    name: event-service
  jackson:
    serialization:
      fail-on-empty-beans: false
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
  data:
    jdbc:
      dialect: postgresql
  datasource:
    url: jdbc:postgresql://event-db:5432/ewm-event
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
logging:
  level:
    org.springframework.orm.jpa: WARN
    org.springframework.transaction: WARN
    org.springframework.transaction.interceptor: WARN
    org.springframework.orm.jpa.JpaTransactionManager: WARN
server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

grpc:
  client:
    analyzer:
      address: 'discovery:///analyzer'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
    collector:
      address: 'discovery:///collector'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
