eureka:
  client:
    registerWithEureka: true
    instance:
      preferIpAddress: true
      lease-renewal-interval-in-seconds: 30
      lease-expiration-duration-in-seconds: 90
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
spring:
  application:
    name: request-service
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations:
            - classpath:config/{application}

grpc:
  client:
    collector:
      address: 'discovery:///collector'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext