spring:
  application:
    name: collector
  jackson:
    serialization:
      fail-on-empty-beans: false
server:
  port: 0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
